public enum SettingTypes
{
    TEST,
    WIN_POS,
    CUR_WIN_POS,
    SCREEN_TIME,
    SENSOR_UPDATE_INTERVAL,
    ACCENT_COLOR,
    AUTOSTART_PANEL,
    AUTOSTART_DELAY_VALUE,
    AUTOSTART_DELAY_TYPE
};